#ifndef E_DISPLAY_ID
#define E_DISPLAY_ID

#define eDispId_ScreenOff                               (  0U)

/** Group 0 **/
#define eDispId_System_Check                            (  1U)
#define eDispId_EOL_Error                               (  2U)
#define eDispId_Welcome                                 (  3U)
#define eDispId_SMK_P_IgnOff                            (  4U)
#define eDispId_Wireless_Charger                        (  5U)
#define eDispId_SunroofWindowHood_Open                  (  6U)
#define eDispId_Goodbye                                 (  7U)
#define eDispId_SBW_VCU2_Warn_IgnOff                    (  8U)
#define eDispId_CheckPattern                            (  9U)
#define eDispId_SEA_IgnOff                              ( 10U)
#define eDispId_Gear_Engaged_IgnOff                     ( 11U)
#define eDispId_RearSeatAlarm_Clear                     ( 12U)
#define eDispId_RearSeatAlarm_Alarm                     ( 13U)
#define eDispId_Batt_LowTemp_IgnOff                     ( 14U)
#define eDispId_SBW_scuNMode_IgnOff                     ( 15U)
#define eDispId_UpdateMode                              ( 16U)


/** Group 1 **/
#define eDispId_FCA_Warn                                ( 20U)
#define eDispId_Engine_HighTemp                         ( 21U)
#define eDispId_EMS_SafetyFunction                      ( 22U)
#define eDispId_DoorHood_Moving_Open                    ( 23U)
#define eDispId_Batt_HighTemp                           ( 24U)
#define eDispId_CheckHevEngine                          ( 25U)
#define eDispId_CheckPowerSupply                        ( 26U)
#define eDispId_AHB_CheckStop                           ( 27U)
#define eDispId_UREA_Abnormal3_Check3                   ( 28U)
#define eDispId_UREA_Shortage4                          ( 29U)
#define eDispId_UREA_Abnormal2_Check2                   ( 30U)
#define eDispId_UREA_Abnormal1_Check1_Stop              ( 31U)
#define eDispId_LowBatToPGear                           ( 32U)
#define eDispId_FCA_Warn_byScc                          ( 33U)
#define eDispId_SBW_ShiftFail                           ( 34U)
#define eDispId_SEA_IgnOn                               ( 35U)
#define eDispId_FCA_LO                                  ( 36U)
#define eDispId_FCA_wESA                                ( 37U)
#define eDispId_FCA_LS                                  ( 38U)
#define eDispId_BCW_Warn                                ( 39U)
#define eDispId_BCA_R                                   ( 40U)
#define eDispId_BCA_R_PLUS                              ( 41U)

/** Group 2-Exception **/
#define eDispId_BVM                                     ( 54U)

/** Group 2-Full **/
#define eDispId_Rheostat                                ( 55U)
#define eDispId_TPMS_SavedNoti                          ( 56U)
#define eDispId_Light                                   ( 57U)
#define eDispId_FrontWiper                              ( 58U)
#define eDispId_RearWiper                               ( 59U)
#define eDispId_Gear_Engaged_IgnOn                      ( 60U)
#define eDispId_SBW_VCU2_Warn_IgnOn                     ( 61U)
#define eDispId_SBW_VCU1_Warn                           ( 62U)
#define eDispId_12VBatteryReset                         ( 63U)
#define eDispId_ADAS_SettingMode                        ( 64U)
#define eDispId_AirCleaning_Onoff                       ( 65U)
#define eDispId_DMS_Fail                                ( 66U)
#define eDispId_FCEV_Regenerate                         ( 67U)
#define eDispId_DriveMode_Full                          ( 68U)
#define eDispId_CSCD_ModeChanged_Full                   ( 69U)
#define eDispId_DriveMode_Error                         ( 70U)

/** Group 2-Mini **/
#define eDispId_IMS                                     ( 75U)
#define eDispId_AV_Mode                                 ( 76U)
#define eDispId_FlexSteer                               ( 77U)
#define eDispId_2StepESC_Off                            ( 78U)
#define eDispId_SCC_ModeChange                          ( 79U)
#define eDispId_BCW_Onoff                               ( 80U)
#define eDispId_CSCD_ModeChanged_Mini                   ( 81U)
#define eDispId_DBC_Onoff                               ( 82U)
#define eDispId_4WD_Onoff                               ( 83U)
#define eDispId_DriveMode_Mini                          ( 84U)

/** Group 3 **/
#define eDispId_PA_ModeChange                           ( 90U)

/** Group 4 **/
#define eDispId_DBC_Cancel                              ( 95U)
#define eDispId_Shift_P_ToCharge                        ( 96U)
#define eDispId_CheckHevNoStart                         ( 97U)
#define eDispId_2WD_Mode                                ( 98U)
#define eDispId_ExhaustGas_TestMode                     ( 99U)
#define eDispId_TPMS_Virgin                             (100U)
#define eDispId_DCT_LimpHome                            (101U)
#define eDispId_DCT_OverHeat                            (102U)
#define eDispId_DCT_HillHold                            (103U)
#define eDispId_HDA_Cancel                              (104U)
#define eDispId_SCC_Popup                               (105U)
#define eDispId_LKAS_HandsOn_Lv1                        (106U)
#define eDispId_LKAS_HandsOn_Lv2_Sound                  (107U)
#define eDispId_LKAS_Cancel                             (108U)
#define eDispId_Attention_Assist                        (109U)
#define eDispId_EPB_Infinite                            (110U)
#define eDispId_ISG_Start                               (111U)
#define eDispId_PA                                      (112U)
#define eDispId_PAS                                     (113U)
#define eDispId_RCTA                                    (114U)
#define eDispId_DCT_CoolingFinish                       (115U)
#define eDispId_ISG_CancelBrakeClutch                   (116U)
#define eDispId_StopToChargeBattery                     (117U)
#define eDispId_InverterCoolant_Refill                  (118U)
#define eDispId_AHB_Check                               (119U)
#define eDispId_PowerDown                               (120U)
#define eDispId_LowBatt_Lv2                             (121U)
#define eDispId_Batt_LowTemp                            (122U)
#define eDispId_PowerLimit                              (123U)
#define eDispId_UREA_Shortage2_3                        (124U)
#define eDispId_HDA_HandsOff2                           (125U)
#define eDispId_DCT_HighTemp                            (126U)
#define eDispId_SCC_SwitchControl                       (127U)
#define eDispId_LKAS_HandsOn_Lv2                        (128U)
#define eDispId_LeadVehicleDeparted                     (129U)
#define eDispId_DCT_Cooling                             (130U)
#define eDispId_HDA_HandsOff1                           (131U)
#define eDispId_HDA_Check_OLD                           (132U)
#define eDispId_NCC                                     (133U)
#define eDispId_HDA_SCCMode                             (134U)
#define eDispId_RegenerateFail                          (135U)
#define eDispId_MDPS                                    (136U)
#define eDispId_HDA_HDAMode                             (137U)
#define eDispId_RCCA                                    (138U)
#define eDispId_HDA_ON_REQ                              (139U)

/** Group 5 **/
#define eDispId_SBW_Engaged_N                           (160U)
#define eDispId_BCM_Warning_P                           (161U)
#define eDispId_SMK_P_IgnOn                             (162U)
#define eDispId_BCM_Warning                             (163U)
#define eDispId_SMK_ExceptParking                       (164U)
#define eDispId_BCM_Warning_Engine                      (165U)
#define eDispId_Remove_Charge                           (166U)
#define eDispId_PHEVFuelTank_Charging                   (167U)
#define eDispId_CSCD_Mode_AutoChange                    (168U)
#define eDispId_Engine_AutoStop                         (169U)
#define eDispId_Heated_Wire_Cancel                      (170U)
#define eDispId_Charging_Alarm                          (171U)
#define eDispId_AuxBattSaverPlus                        (172U)
#define eDispId_FCEV_ChargeFinish                       (173U)
#define eDispId_FCEV_CheckFuelInlet                     (174U)
#define eDispId_ChargeDoor_Open                         (175U)
#define eDispId_SEA_Operation_fail                      (176U)
#define eDispId_SEA_Operation_noti                      (177U)
#define eDispId_SBW_scuNMode_IgnOn                      (178U)
#define eDispId_PHEVFuelTank_WaitOrFuel                 (179U)
#define eDispId_SMK_Shift_N_Start                       (180U)
#define eDispId_SMK_iMT_Start                           (181U)

/** Group 6 **/
#define eDispId_TCF                                     (190U)
#define eDispId_Service_Reminder                        (191U)
#define eDispId_BatteryDischargeWarning                 (192U)

/** Factory Mode (Screen Test) **/
#define eDispId_FactoryScreen                           (199U)

/** Group 7 **/
#define eDispId_AAF_Fail                                (200U)
#define eDispId_LEDHeadLamp_Fail                        (201U)
#define eDispId_PSB_Fail                                (202U)
#define eDispId_BCA_Fail                                (203U)
#define eDispId_BCW_Fail                                (204U)
#define eDispId_TPMS_Warn                               (205U)
#define eDispId_SCC_SystemFail                          (206U)
#define eDispId_FCA_Fail                                (207U)
#define eDispId_FCW_Fail                                (208U)
#define eDispId_BCW_Blockage                            (209U)
#define eDispId_SCC_Blockage                            (210U)
#define eDispId_FCA_Blockage                            (211U)
#define eDispId_LKAS_Fail                               (212U)
#define eDispId_EVSystem_Check                          (213U)
#define eDispId_PA_Fail                                 (214U)
#define eDispId_PAS_Fail                                (215U)
#define eDispId_NormalChargeError                       (216U)
#define eDispId_ECS_Fail                                (217U)
#define eDispId_LowEngineOil                            (218U)
#define eDispId_CoolingWaterFilter_Check                (219U)
#define eDispId_LowWasher                               (220U)
#define eDispId_DPF_Fail                                (221U)
#define eDispId_StopLamp_Fail                           (222U)
#define eDispId_HighMountedStopLamp_Fail                (223U)
#define eDispId_HeadLamp_Bifunc_Fail                    (224U)
#define eDispId_HeadLamp_Low_Fail                       (225U)
#define eDispId_StaticBendingLamp_Fail                  (226U)
#define eDispId_DynamicBendingLamp_Fail                 (227U)
#define eDispId_HeadLamp_High_Fail                      (228U)
#define eDispId_DayLightLamp_Fail                       (229U)
#define eDispId_FogLamp_Fail                            (230U)
#define eDispId_TailLamp_Fail                           (231U)
#define eDispId_PositionLamp_Fail                       (232U)
#define eDispId_TurnSignalLamp_Fail                     (233U)
#define eDispId_LicensePlateLamp_Fail                   (234U)
#define eDispId_Haptic_Fail                             (235U)
#define eDispId_Refuel                                  (236U)
#define eDispId_HDA_Check                               (237U)
#define eDispId_LowFuel                                 (238U)
#define eDispId_UREA_Shortage1                          (239U)
#define eDispId_LowBatt_Lv1                             (240U)
#define eDispId_VESS_Fail                               (241U)
#define eDispId_ISLW_Fail                               (242U)
#define eDispId_HBA_Fail                                (243U)
#define eDispId_FCW_Blockage                            (244U)
#define eDispId_ISLW_Blockage                           (245U)
#define eDispId_RemainChargeTime                        (246U)
#define eDispId_ExtFastCharge_Fail                      (247U)
#define eDispId_ExtSlowCharge_Fail                      (248U)
#define eDispId_CheckHev                                (249U)
#define eDispId_FuelRunOut                              (250U)
#define eDispId_ChargeDoor_OpenMoving                   (251U)
#define eDispId_ParasiticCurrent                        (252U)
#define eDispId_PHEVFuelTank_CheckOrOpen                (253U)
#define eDispId_SBW_LVR_Fail                            (254U)
#define eDispId_IceWarning                              (255U)
#define eDispId_SCUOverHeat                             (256U)
#define eDispId_CheckDiffGear                           (257U)
#define eDispId_CoolingWater_Refill                     (258U)
#define eDispId_OilFilter_Check                         (259U)
#define eDispId_CheckBrake_ABSESC                       (260U)
#define eDispId_CheckBrake_BrakeFluid                   (261U)
#define eDispId_Check48VePT                             (262U)
#define eDispId_CheckTireDiff                           (263U)
#define eDispId_CheckBrake_VacuumPump                   (264U)
#define eDispId_FCEV_FuelCellFCEVCoolantShortage        (265U)
#define eDispId_EV_Ready                                (266U)
#define eDispId_RegenBrakeSystem_Fail                   (267U)
#define eDispId_TPMS_Warn_Inform                        (268U)
#define eDispId_CheckRearSeatAlarm                      (269U)
#define eDispId_SBW_LVR_Fail_IgnOff                     (270U)
#define eDispId_BCW_Off_Noti                            (271U)
#define eDispId_BCA_Blockage                            (272U)

/** Group 8 **/
#define eDispId_DoorTrunkHood_Stopped_Open              (294U)

/** GroupTab **/
#define eDispId_GroupTab                                (295U)

#define eDispId_Max                                     (296U)


#endif  /* E_DISPLAY_ID */

