#ifndef E_DISPLAY_ID
#define E_DISPLAY_ID

#define eDispId_ScreenOff                               (  0U)

/** Group 0 **/
#define eDispId_System_Check                            (  1U)
#define eDispId_EOL_Error                               (  2U)
#define eDispId_Welcome                                 (  3U)
#define eDispId_SMK_P_IgnOff                            (  4U)
#define eDispId_Wireless_Charger                        (  5U)
#define eDispId_SunroofWindowHood_Open                  (  6U)
#define eDispId_Goodbye                                 (  7U)
#define eDispId_SBW_VCU2_Warn_IgnOff                    (  8U)
#define eDispId_CheckPattern                            (  9U)
#define eDispId_SEA_IgnOff                              ( 10U)
#define eDispId_Gear_Engaged_IgnOff                     ( 11U)
#define eDispId_RearSeatAlarm_Clear                     ( 12U)
#define eDispId_RearSeatAlarm_Alarm                     ( 13U)
#define eDispId_Batt_LowTemp_IgnOff                     ( 14U)
#define eDispId_SBW_scuNMode_IgnOff                     ( 15U)
#define eDispId_UpdateMode                              ( 16U)


/** Group 1 **/
#define eDispId_FCA_Warn                                ( 20U)
#define eDispId_Engine_HighTemp                         ( 21U)
#define eDispId_EMS_SafetyFunction                      ( 22U)
#define eDispId_DoorHood_Moving_Open                    ( 23U)
#define eDispId_Batt_HighTemp                           ( 24U)
#define eDispId_CheckHevEngine                          ( 25U)
#define eDispId_CheckPowerSupply                        ( 26U)
#define eDispId_AHB_CheckStop                           ( 27U)
#define eDispId_UREA_Abnormal3_Check3                   ( 28U)
#define eDispId_UREA_Shortage4                          ( 29U)
#define eDispId_UREA_Abnormal2_Check2                   ( 30U)
#define eDispId_UREA_Abnormal1_Check1_Stop              ( 31U)
#define eDispId_LowBatToPGear                           ( 32U)
#define eDispId_FCA_Warn_byScc                          ( 33U)
#define eDispId_SBW_ShiftFail                           ( 34U)
#define eDispId_SEA_IgnOn                               ( 35U)
#define eDispId_FCA_LO                                  ( 36U)
#define eDispId_FCA_wESA                                ( 37U)
#define eDispId_FCA_LS                                  ( 38U)
#define eDispId_BCW_Warn                                ( 39U)
#define eDispId_BCA_R                                   ( 40U)
#define eDispId_BCA_R_PLUS                              ( 41U)
#define eDispId_HDA_Cancel                              ( 42U)
#define eDispId_HDA_HandsOff2                           ( 43U)
#define eDispId_LKAS_Cancel                             ( 44U)
#define eDispId_LKAS_HandsOn_Lv2                        ( 45U)
#define eDispId_LKAS_HandsOn_Lv2_Sound                  ( 46U)
#define eDispId_HDA_HandsOff1                           ( 47U)
#define eDispId_LKAS_HandsOn_Lv1                        ( 48U)
#define eDispId_HDA_SCCMode                             ( 49U)
